version: 2.1
jobs:
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.1
    resource_class: small
    steps:
      - run:
          name: Install dependencies
          command: apk add bash git openssh-client grep
      - checkout
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_deb_pkg:
    docker:
      - image: cimg/base:stable
    # We're doing a remote Docker build, so we don't need local resources.
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
      - run:
          name: Enable multiarch builds with QEMU
          command: |
            docker run \
              --rm \
              --privileged \
              multiarch/qemu-user-static \
              --reset \
              -p yes
      - run:
          name: Create multiarch build context
          command: docker context create builder
      - run:
          name: Create multiplatform builder
          command: |
            docker buildx create builder \
              --name builder \
              --driver docker-container \
              --use
      - run:
          name: Ensure builder has booted
          command: docker buildx inspect --bootstrap
      - run:
          name: Build docker image with .deb package
          command: |
            docker buildx build \
              --platform linux/arm/v7 \
              --build-arg PKG_VERSION="$(date '+%Y%m%d%H%M%S')" \
              --target=artifact \
              --progress=plain \
              --output type=local,dest=$(pwd)/releases/ \
              .
      - run:
          name: List contents of Debian package
          command: dpkg --contents releases/janus*.deb
      - store_artifacts:
          path: releases
workflows:
  build:
    jobs:
      - check_bash
      - build_deb_pkg
