version: 2.1
executors:
  ubuntu:
    docker:
      - image: cimg/base:2024.02
jobs:
  check_bash:
    executor: ubuntu
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install ShellCheck
          command: |
            set -eux
            readonly SHELLCHECK_VERSION='v0.9.0'
            wget --quiet --output-document - \
              "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" |
              tar --extract --xz --verbose
            cd "./shellcheck-${SHELLCHECK_VERSION}"
            sudo cp shellcheck /usr/bin
            shellcheck --version
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_debian_package:
    executor: ubuntu
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Debian package
          command: ./dev-scripts/build-debian-pkg 'linux/arm/v7'
      - run:
          name: Print Debian package contents
          command: |
            set -exu
            while read -r file; do
              dpkg --contents "${file}"
            done < <(find . -name '*.deb')
      - store_artifacts:
          path: build
workflows:
  build:
    jobs:
      - check_bash
      - build_debian_package
