version: 2.1
executors:
  ubuntu:
    docker:
      - image: cimg/base:2024.02
jobs:
  check_whitespace:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  check_bash:
    executor: ubuntu
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install ShellCheck
          command: |
            set -eux
            readonly SHELLCHECK_VERSION='v0.9.0'
            wget --quiet --output-document - \
              "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" |
              tar --extract --xz --verbose
            cd "./shellcheck-${SHELLCHECK_VERSION}"
            sudo cp shellcheck /usr/bin
            shellcheck --version
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_debian_package:
    executor: ubuntu
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Debian package
          command: ./dev-scripts/build-debian-pkg 'linux/arm/v7'
      - persist_to_workspace:
          root: build
          paths:
            - "*.deb"
      - store_artifacts:
          path: build
  check_debian_package:
    executor: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install lintian build tools
          command: |
            set -eux
            sudo apt-get update
            sudo apt-get install --yes devscripts equivs git
      - run:
          name: Clone lintian source
          command: |
            set -eux
            git clone \
              --depth 1 \
              --branch 2.130.1 \
              https://salsa.debian.org/lintian/lintian.git \
              /tmp/lintian-build
      - run:
          name: Install lintian build dependencies
          command: |
            set -eux
            cd /tmp/lintian-build
            DEB_BUILD_PROFILES='nocheck nodoc' \
              sudo mk-build-deps \
                --install \
                --remove \
                --tool 'sudo apt-get --no-install-recommends --yes' \
                debian/control
      - run:
          name: Build and install lintian
          command: |
            set -eux
            cd /tmp/lintian-build
            dpkg-buildpackage \
              --unsigned-source \
              --unsigned-changes \
              --build=binary \
              --build-profiles=nocheck,nodoc
            sudo apt-get install --yes /tmp/lintian_*.deb
      - run:
          name: Print lintian version
          command: lintian --version
      - run:
          name: Run static analysis on Debian package
          command: ./dev-scripts/check-debian-pkg
workflows:
  build:
    jobs:
      - check_whitespace
      - check_bash
      - build_debian_package
      - check_debian_package:
          requires:
            - build_debian_package
