version: 2.1
executors:
  ubuntu:
    docker:
      - image: cimg/base:2024.02
  debian:
    docker:
      - image: debian:trixie-20260202-slim
jobs:
  check_whitespace:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  check_bash:
    executor: ubuntu
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install ShellCheck
          command: |
            set -eux
            readonly SHELLCHECK_VERSION='v0.9.0'
            wget --quiet --output-document - \
              "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" |
              tar --extract --xz --verbose
            cd "./shellcheck-${SHELLCHECK_VERSION}"
            sudo cp shellcheck /usr/bin
            shellcheck --version
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  build_debian_package:
    executor: ubuntu
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Debian package
          command: ./dev-scripts/build-debian-pkg 'linux/arm/v7'
      - persist_to_workspace:
          root: build
          paths:
            - "*.deb"
      - store_artifacts:
          path: build
  check_debian_package:
    executor: debian
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - v1-lintian-2.130.1
      - run:
          name: Build lintian .deb
          command: |
            set -eux
            if [[ -f ~/lintian-cache/lintian.deb ]]; then
              exit 0
            fi
            # Install build tools.
            apt-get update
            apt-get install --yes devscripts equivs git

            # Clone source.
            git clone \
              --depth 1 \
              --branch 2.130.1 \
              https://salsa.debian.org/lintian/lintian.git \
              /tmp/lintian-build

            # Install build dependencies.
            cd /tmp/lintian-build
            DEB_BUILD_PROFILES='nocheck nodoc' \
              mk-build-deps \
                --install \
                --remove \
                --tool 'apt-get --no-install-recommends --yes' \
                debian/control

            # Build and cache the .deb.
            dpkg-buildpackage \
              --unsigned-source \
              --unsigned-changes \
              --build=binary \
              --build-profiles=nocheck,nodoc
            mkdir --parents ~/lintian-cache
            cp /tmp/lintian_*.deb ~/lintian-cache/lintian.deb
      - save_cache:
          key: v1-lintian-2.130.1
          paths:
            - ~/lintian-cache
      - run:
          name: Install lintian
          command: apt-get install --yes ~/lintian-cache/lintian.deb
      - run:
          name: Print lintian version
          command: lintian --version
      - run:
          name: Run static analysis on Debian package
          command: ./dev-scripts/check-debian-pkg
workflows:
  build:
    jobs:
      - check_whitespace
      - check_bash
      - build_debian_package
      - check_debian_package:
          requires:
            - build_debian_package
