version: 2.1
executors:
  ubuntu-machine:
    machine:
      image: ubuntu-2204:2024.01.2
jobs:
  check_bash:
    # Use machine executor to allow for mounting a filesystem.
    executor: ubuntu-machine
    steps:
      - checkout
      - run:
          name: Install BATS
          command: |
            set -eux
            git clone --branch v1.10.0 --depth 1 \
              https://github.com/bats-core/bats-core.git
            cd ./bats-core
            sudo ./install.sh /usr
            bats --version
      - run:
          name: Install ShellCheck
          command: |
            set -eux
            readonly SHELLCHECK_VERSION='v0.9.0'
            wget --quiet --output-document - \
              "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" |
              tar --extract --xz --verbose
            cd "./shellcheck-${SHELLCHECK_VERSION}"
            sudo cp shellcheck /usr/bin
            shellcheck --version
      - run:
          name: Run tests and static analysis on bash scripts
          command: sudo ./dev-scripts/check-bash
  build_deb_pkg:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Create build context
          command: docker context create builder
      - run:
          name: Create builder
          command: |
            docker buildx create builder \
              --name builder \
              --driver docker-container \
              --use
      - run:
          name: Ensure builder has booted
          command: docker buildx inspect --bootstrap
      - run:
          name: Build docker image with .deb package
          command: |
            docker buildx build \
              --platform linux/arm/v7 \
              --build-arg PKG_VERSION="$(date '+%Y%m%d%H%M%S')" \
              --target=artifact \
              --progress=plain \
              --output type=local,dest=$(pwd)/releases/ \
              .
      - run:
          name: List contents of Debian package
          command: dpkg --contents releases/janus*.deb
      - store_artifacts:
          path: releases
workflows:
  build:
    jobs:
      - check_bash
      - build_deb_pkg
